-- ==============================================================================
-- FlowRun — Migration 0013: Seed planes pro Sarah McCormack (5 planes)
-- ==============================================================================
-- Generado automáticamente desde discovery/pro-plans/sarah-mccormack-plans.md
-- por supabase/migrations/generate_0013_pro_seed.py
-- ==============================================================================

-- ----------------------------------------------------------------------
-- TRAIL-10K — Trail 10K
-- ----------------------------------------------------------------------
insert into public.plan_templates
  (code, name, description, goal_type, experience_level, weekly_days, total_weeks, is_pro)
values
  ('trail_10k', 'Trail 10K', 'Plan de 10 semanas para trail 10K. Prerequisito: Mínimo 4 días de corrida por semana', 'trail', 'advanced', 6, 10, true)
on conflict (code) do nothing;

with t as (select id from public.plan_templates where code = 'trail_10k')
insert into public.template_sessions
  (template_id, week_number, day_index, session_name, blocks, total_duration_min, distance_label, is_deload)
select t.id, w, d, name, b::jsonb, dur, dist, false from t,
(values
  (1, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"Hill reps piramidal: 60s - 90s - 2 min - 3 min - 2 min - 90s - 60s duro cuesta arriba. Trotar bajada después de cada rep"}]', 45, NULL),
  (1, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30}]', 30, '3 mi'),
  (1, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (1, 4, 'Aceleraciones', '[{"code":"SU","duration_min":45,"note":"Flat surges: 6 x (20s rápido / 3 min trote easy)"}]', 45, NULL),
  (1, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (1, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":66}]', 66, '6 mi'),
  (2, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 2.5 min duro cuesta arriba, bajada trote easy"}]', 45, NULL),
  (2, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (2, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (2, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (2, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":77}]', 77, '7 mi'),
  (3, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 3 min duro cuesta arriba, bajada trote easy"}]', 45, NULL),
  (3, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30}]', 30, '3 mi'),
  (3, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (3, 4, 'Tempo', '[{"code":"TE","duration_min":40,"note":"Steady tempo: 15 min · Esfuerzo: 2h race pace"}]', 40, NULL),
  (3, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (3, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":88}]', 88, '8 mi'),
  (4, 1, 'Aceleraciones', '[{"code":"SU","duration_min":45,"note":"Uphill surges: 6 x (30s rápido cuesta arriba / 2 min bajada y llano trote)"}]', 45, NULL),
  (4, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (4, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (4, 4, 'Progresivo', '[{"code":"PR","duration_min":95,"note":"10 min @ 2h race pace (75-80%) + 5 min @ 40-60 min race pace (90-95%)"}]', 95, NULL),
  (4, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (4, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":99}]', 99, '9 mi'),
  (5, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"4 x (4 min duro cuesta arriba / trote bajada)"}]', 45, NULL),
  (5, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (5, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (5, 4, 'Aceleraciones', '[{"code":"SU","duration_min":45,"note":"Flat surges: 6 x (20s rápido / 3 min trote easy)"}]', 45, NULL),
  (5, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (5, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":77}]', 77, '7 mi'),
  (6, 1, 'Tempo', '[{"code":"TE","duration_min":45,"note":"Steady tempo: 20 min · Esfuerzo: 2h race pace"}]', 45, NULL),
  (6, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (6, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (6, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"6 x (3 min fast tempo / 90s trote easy). 1h race pace (90%) en los 3 min"}]', 45, NULL),
  (6, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (6, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":110}]', 110, '10 mi'),
  (7, 1, 'Hill Fartlek', '[{"code":"HF","duration_min":50,"note":"25 min ondulada: duro en subidas, easy en llano y bajadas"}]', 50, NULL),
  (7, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (7, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (7, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (7, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":88,"note":"Con pickup: 5 mi easy + 2 mi @ 1.5h race pace (80%) + 1 mi easy"}]', 88, '8 mi'),
  (8, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"1-4-1-4-1-4 min duro cuesta arriba, trote bajada entre reps"}]', 45, NULL),
  (8, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (8, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (8, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"6 x (4 min fast tempo / 2 min trote easy). 1h race pace (90%) en los 4 min"}]', 45, NULL),
  (8, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (8, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":99}]', 99, '9 mi'),
  (9, 1, 'Tempo', '[{"code":"TE","duration_min":50,"note":"Steady tempo: 25 min · Esfuerzo: 2h race pace"}]', 50, NULL),
  (9, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (9, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (9, 4, 'Hill Fartlek', '[{"code":"HF","duration_min":55,"note":"30 min ondulada: duro en subidas, easy en llano y bajadas"}]', 55, NULL),
  (9, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (9, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":77}]', 77, '7 mi'),
  (10, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"3-2-1-30s-3-2-1-30s min rápido pero relajado, 2 min trote entre. 1h race pace en 3 y 2 min; 30 min race pace en 1 min y 30s. Terminar con energía"}]', 45, NULL),
  (10, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (10, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"Con 4 x 10s strides relajados"}]', 30, '3 mi'),
  (10, 4, '¡Tu carrera!', '[{"code":"RC","duration_min":60}]', 60, NULL)
) as s(w, d, name, b, dur, dist)
on conflict (template_id, week_number, day_index) do nothing;

-- ----------------------------------------------------------------------
-- TRAIL-HALF — Trail Half Marathon
-- ----------------------------------------------------------------------
insert into public.plan_templates
  (code, name, description, goal_type, experience_level, weekly_days, total_weeks, is_pro)
values
  ('trail_half', 'Trail Half Marathon', 'Plan de 10 semanas para trail half marathon. Distancia oficial 13.1 mi pero pueden ir de 12 a 15 mi. Prerequisito: 5-6 días de corrida por semana acumulando 30-40 millas semanales', 'trail', 'advanced', 6, 10, true)
on conflict (code) do nothing;

with t as (select id from public.plan_templates where code = 'trail_half')
insert into public.template_sessions
  (template_id, week_number, day_index, session_name, blocks, total_duration_min, distance_label, is_deload)
select t.id, w, d, name, b::jsonb, dur, dist, false from t,
(values
  (1, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 1 min duro cuesta arriba + 5 x 30s duro cuesta arriba. Trote a punto de partida entre reps"}]', 45, NULL),
  (1, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (1, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (1, 4, 'Tempo', '[{"code":"TE","duration_min":40,"note":"Steady tempo: 15 min · Esfuerzo: 2h race pace"}]', 40, NULL),
  (1, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (1, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":88}]', 88, '8 mi'),
  (2, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"6 x 2 min duro cuesta arriba, trote a punto de partida entre reps"}]', 45, NULL),
  (2, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (2, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (2, 4, 'Aceleraciones', '[{"code":"SU","duration_min":45,"note":"Flat surges: 6 x (20s rápido / 3 min trote easy)"}]', 45, NULL),
  (2, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (2, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":99}]', 99, '9 mi'),
  (3, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"6 x 3 min duro cuesta arriba, trote a punto de partida entre reps"}]', 45, NULL),
  (3, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (3, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (3, 4, 'Tempo', '[{"code":"TE","duration_min":45,"note":"Steady tempo: 20 min · Esfuerzo: 2h race pace"}]', 45, NULL),
  (3, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (3, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":110}]', 110, '10 mi'),
  (4, 1, 'Tempo', '[{"code":"TE","duration_min":50,"note":"Steady tempo: 25 min · Esfuerzo: 2h race pace"}]', 50, NULL),
  (4, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (4, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (4, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"4 x (5 min fast tempo / 2 min trote easy). 1h race pace (90%) en los reps"}]', 45, NULL),
  (4, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (4, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":132}]', 132, '12 mi'),
  (5, 1, 'Aceleraciones', '[{"code":"SU","duration_min":45,"note":"Flat surges: 6 x (20s rápido / 3 min trote easy)"}]', 45, NULL),
  (5, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (5, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (5, 4, 'Progresivo', '[{"code":"PR","duration_min":40,"note":"10 min @ 2h race pace (75-80%) + 10 min @ 1h race pace (90-95%)"}]', 40, NULL),
  (5, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (5, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":121,"note":"Con pickup: 8 mi easy + 2 mi @ 1.5h race pace (80%) + 1 mi easy"}]', 121, '11 mi'),
  (6, 1, 'Hill Fartlek', '[{"code":"HF","duration_min":50,"note":"25 min ondulada: duro en subidas, easy en llano y bajadas"}]', 50, NULL),
  (6, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (6, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":30}]', 30, '3 mi'),
  (6, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"5 x (5 min fast tempo / 2 min trote easy). 1h race pace en los 5 min"}]', 45, NULL),
  (6, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (6, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":154}]', 154, '14 mi'),
  (7, 1, 'Tempo', '[{"code":"TE","duration_min":55,"note":"Steady tempo: 30 min · Esfuerzo: 2h race pace"}]', 55, NULL),
  (7, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (7, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (7, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"3 x (8 min fast tempo / 3 min trote easy). 1h race pace en los 8 min"}]', 45, NULL),
  (7, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (7, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":165}]', 165, '15 mi'),
  (8, 1, 'Progresivo', '[{"code":"PR","duration_min":50,"note":"15 min @ 2h race pace (75-80%) + 15 min @ 1h race pace (90-95%)"}]', 50, NULL),
  (8, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (8, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (8, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"3 x (10 min fast tempo / 3 min trote easy). 1h race pace en los 10 min"}]', 45, NULL),
  (8, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (8, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":132}]', 132, '12 mi'),
  (9, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"2 x 4 min duro cuesta arriba con trote bajada. Después: 20 min de tempo ondulado @ 1.5h race pace (80-90%)"}]', 45, NULL),
  (9, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (9, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (9, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"8-6-4-4 min fast tempo con 2 min trote entre reps. 1h race pace (90%)"}]', 45, NULL),
  (9, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (9, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":88}]', 88, '8 mi'),
  (10, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"5-3-3-1-1 min con 3 min trote entre reps. 1.5h race pace en el 5 min; 1h race pace en los 3 min; 30 min race pace en los 1 min. Terminar con energía"}]', 45, NULL),
  (10, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (10, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"Con 4 x 10s strides relajados"}]', 30, '3 mi'),
  (10, 4, '¡Tu carrera!', '[{"code":"RC","duration_min":60}]', 60, NULL)
) as s(w, d, name, b, dur, dist)
on conflict (template_id, week_number, day_index) do nothing;

-- ----------------------------------------------------------------------
-- TRAIL-MARATHON — Trail Marathon
-- ----------------------------------------------------------------------
insert into public.plan_templates
  (code, name, description, goal_type, experience_level, weekly_days, total_weeks, is_pro)
values
  ('trail_marathon', 'Trail Marathon', 'Plan de 16 semanas para trail marathon. Long runs con porcentaje del desnivel total de tu carrera. Prerequisito: 5-6 días de corrida por semana acumulando al menos 30-40 millas semanales', 'trail', 'advanced', 6, 16, true)
on conflict (code) do nothing;

with t as (select id from public.plan_templates where code = 'trail_marathon')
insert into public.template_sessions
  (template_id, week_number, day_index, session_name, blocks, total_duration_min, distance_label, is_deload)
select t.id, w, d, name, b::jsonb, dur, dist, false from t,
(values
  (1, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"4 x 4 min fast tempo / 2 min trote easy. 1h race pace (90%)"}]', 45, NULL),
  (1, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (1, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (1, 4, 'Tempo', '[{"code":"TE","duration_min":40,"note":"15 min · Esfuerzo: 2h race pace"}]', 40, NULL),
  (1, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (1, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":88}]', 88, '8 mi'),
  (2, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"6-4-4-6 min fast / 2 min trote easy. 1h race pace (90%)"}]', 45, NULL),
  (2, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (2, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (2, 4, 'Tempo', '[{"code":"TE","duration_min":45,"note":"20 min · Esfuerzo: 2h race pace"}]', 45, NULL),
  (2, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (2, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":99}]', 99, '9 mi'),
  (3, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"4 x 2.5 min duro cuesta arriba, trote a punto de partida. Ritmo más rápido sostenible y consistente"}]', 45, NULL),
  (3, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (3, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (3, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"6-4-2-2-4-6 min fast / 2 min trote easy. 1h race pace (90%)"}]', 45, NULL),
  (3, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (3, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":110}]', 110, '10 mi'),
  (4, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"6 x 4 min fast tempo / 2 min trote easy. 1h race pace (90%)"}]', 45, NULL),
  (4, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (4, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (4, 4, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 2.5 min duro cuesta arriba, trote bajada. Ritmo más rápido sostenible y consistente"}]', 45, NULL),
  (4, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (4, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":121}]', 121, '11 mi'),
  (5, 1, 'Hill Fartlek', '[{"code":"HF","duration_min":45,"note":"20 min ondulada: duro en subidas (entre 20-min race pace en cortas y 90-min race pace en largas), easy en llano y bajadas"}]', 45, NULL),
  (5, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (5, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (5, 4, 'Tempo', '[{"code":"TE","duration_min":37,"note":"2 x 12 min @ 2h race pace (75-80%) con 3 min trote entre reps · Buen día para probar tu estrategia de combustible (*)."}]', 37, NULL),
  (5, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (5, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":143}]', 143, '13 mi'),
  (6, 1, 'Progresivo', '[{"code":"PR","duration_min":60,"note":"20 min total: 10 min @ 2h race pace (75-80%) + 10 min @ 1h race pace (90-95%)"}]', 60, NULL),
  (6, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (6, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":60,"note":"(o descanso)"}]', 60, '6 mi'),
  (6, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"Con 6 x 20s strides, 2-3 min trote easy entre cada aceleración"}]', 40, '4 mi'),
  (6, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (6, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":99,"note":"En los últimos 10-15 min: 5 x 30s surges (no más rápido que 10k race pace) con 2-3 min trote entre, en llano firme"}]', 99, '9 mi'),
  (7, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"8-4-6-4-4 min fast / 2 min trote easy entre reps. 1h race pace (90%)"}]', 45, NULL),
  (7, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (7, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (7, 4, 'Tempo', '[{"code":"TE","duration_min":40,"note":"2 x 15 min @ 2h race pace (75-80%) con 3 min trote entre reps · Buen día para probar tu estrategia de combustible (*)."}]', 40, NULL),
  (7, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (7, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":165}]', 165, '15 mi'),
  (8, 1, 'Hill Fartlek', '[{"code":"HF","duration_min":50,"note":"25 min ondulada: duro en subidas (20-min a 90-min race pace según largo), easy en llano y bajadas"}]', 50, NULL),
  (8, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":70}]', 70, '7 mi'),
  (8, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (8, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60,"note":"Con 6 x 20s strides, 2-3 min trote easy entre"}]', 60, '6 mi'),
  (8, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (8, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":132,"note":"En las últimas 3 mi: 10 min @ 2h race pace (75-80%)"}]', 132, '12 mi'),
  (9, 1, 'Tempo', '[{"code":"TE","duration_min":45,"note":"En trail ondulado, 20 min @ 1h race pace (90-95%)"}]', 45, NULL),
  (9, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (9, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (9, 4, 'Progresivo', '[{"code":"PR","duration_min":70,"note":"25 min total: 10 min @ 3h race pace (65-70%) + 10 min @ 2h race pace (75-80%) + 5 min @ 1h race pace (90-95%) · Buen día para probar tu estrategia de combustible (*)."}]', 70, NULL),
  (9, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (9, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":187}]', 187, '17 mi'),
  (10, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"4 x 4 min duro cuesta arriba, trote bajada. Ritmo más rápido sostenible y consistente"}]', 45, NULL),
  (10, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":70}]', 70, '7 mi'),
  (10, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (10, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"Con 6 x 20s strides, 2-3 min trote easy entre"}]', 40, '4 mi'),
  (10, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (10, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":110,"note":"Incluí 3 x 10 min @ 2h race pace (75-80%) con 5 min trote entre reps · Buen día para probar tu estrategia de combustible (*)."}]', 110, '10 mi'),
  (11, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"3 x 10 min fast / 3 min trote easy entre. 1h race pace (90%). Pasalo a miércoles si seguís cansado del domingo"}]', 45, NULL),
  (11, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (11, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (11, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"Con 6 x 20s strides, 2-3 min trote easy entre"}]', 40, '4 mi'),
  (11, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (11, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":220}]', 220, '20 mi'),
  (12, 1, 'Progresivo', '[{"code":"PR","duration_min":80,"note":"30 min total: 10 min @ 3h race pace (65-70%) + 10 min @ 2h race pace (75-80%) + 10 min @ 1h race pace (90-95%) · Buen día para probar tu estrategia de combustible (*)."}]', 80, NULL),
  (12, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (12, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (12, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60,"note":"Con 6 x 20s strides, 2-3 min trote easy entre"}]', 60, '6 mi'),
  (12, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (12, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":110,"note":"Incluí 3 x 15 min @ 3h race pace (65-70%) con 5 min trote entre reps. ALTERNATIVA: 10-mile o half marathon de trail como carrera de preparación · Buen día para probar tu estrategia de combustible (*)."}]', 110, '10 mi'),
  (13, 1, 'Hill Fartlek', '[{"code":"HF","duration_min":55,"note":"30 min ondulada: duro en subidas, easy en llano y bajadas"}]', 55, NULL),
  (13, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (13, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (13, 4, 'Tempo', '[{"code":"TE","duration_min":65,"note":"40 min @ 3h race pace (65-75%) · Buen día para probar tu estrategia de combustible (*)."}]', 65, NULL),
  (13, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (13, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":198}]', 198, '18 mi'),
  (14, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 4 min duro cuesta arriba, trote bajada. Ritmo más rápido sostenible y consistente"}]', 45, NULL),
  (14, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":70}]', 70, '7 mi'),
  (14, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":50,"note":"(o descanso)"}]', 50, '5 mi'),
  (14, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"Con 6 x 20s strides, 2-3 min trote easy entre"}]', 40, '4 mi'),
  (14, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (14, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":154,"note":"Incluí 2 x 20 min @ 3h race pace (65-70%) con 5 min trote entre reps · Buen día para probar tu estrategia de combustible (*)."}]', 154, '14 mi'),
  (15, 1, 'Progresivo', '[{"code":"PR","duration_min":80,"note":"30 min total: 20 min @ 3h race pace (65-70%) + 10 min @ 1h race pace (90-95%) · Buen día para probar tu estrategia de combustible (*)."}]', 80, NULL),
  (15, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (15, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (15, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"4 x 4 min fast tempo / 2 min trote easy. 1h race pace (90%)"}]', 45, NULL),
  (15, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"(o descanso)"}]', 40, '4 mi'),
  (15, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":77}]', 77, '7 mi'),
  (16, 1, 'Tempo', '[{"code":"TE","duration_min":35,"note":"10 min steady · Esfuerzo: 3h race pace"}]', 35, NULL),
  (16, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (16, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"Con 6 x 20s strides rápidos pero no extenuantes, 2-3 min trote easy entre"}]', 30, '3 mi'),
  (16, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":20,"note":"(o descanso)"}]', 20, '2 mi'),
  (16, 5, '¡Tu carrera!', '[{"code":"RC","duration_min":60}]', 60, NULL)
) as s(w, d, name, b, dur, dist)
on conflict (template_id, week_number, day_index) do nothing;

-- ----------------------------------------------------------------------
-- 50-MILE-BEGINNER — 50 Mile Beginner
-- ----------------------------------------------------------------------
insert into public.plan_templates
  (code, name, description, goal_type, experience_level, weekly_days, total_weeks, is_pro)
values
  ('50_mile_beginner', '50 Mile Beginner', 'Plan de 16 semanas para 50 millas. Incluye caminatas largas en cerro para entrenar el caminar en carrera. Prerequisito: Haber completado al menos un trail half marathon. Corre regularmente hace menos de 2 años o no acostumbrado a sesiones estructuradas de velocidad', 'trail', 'advanced', 5, 16, true)
on conflict (code) do nothing;

with t as (select id from public.plan_templates where code = '50_mile_beginner')
insert into public.template_sessions
  (template_id, week_number, day_index, session_name, blocks, total_duration_min, distance_label, is_deload)
select t.id, w, d, name, b::jsonb, dur, dist, false from t,
(values
  (1, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (1, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (1, 3, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 2 min duro cuesta arriba, trote a punto de partida. Ritmo más rápido sostenible y consistente"}]', 45, NULL),
  (1, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (1, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":110}]', 110, '10 mi'),
  (2, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (2, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (2, 3, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 2.5 min duro cuesta arriba, trote a punto de partida"}]', 45, NULL),
  (2, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (2, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":132}]', 132, '12 mi'),
  (3, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (3, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (3, 3, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 3 min duro cuesta arriba, trote a punto de partida"}]', 45, NULL),
  (3, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (3, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":154}]', 154, '14 mi'),
  (4, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (4, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (4, 3, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"4 x 2 min duro cuesta arriba, trote a punto de partida"}]', 45, NULL),
  (4, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (4, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":132}]', 132, '12 mi'),
  (5, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (5, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (5, 3, 'Tempo', '[{"code":"TE","duration_min":40,"note":"15 min · Esfuerzo: 3h race pace · Buen día para probar tu estrategia de combustible (*)."}]', 40, NULL),
  (5, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":30}]', 30, '3 mi'),
  (5, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":176,"note":"Buen día para probar tu estrategia de combustible (*)."}]', 176, '16 mi'),
  (6, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (6, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (6, 3, 'Hill Fartlek', '[{"code":"HF","duration_min":45,"note":"20 min ondulada: duro en subidas (40-60 min race pace), easy en llano y bajadas"}]', 45, NULL),
  (6, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (6, 5, 'Caminata Larga', '[{"code":"HK","duration_min":300,"note":"Caminata en cerro de 4-5 h"}]', 300, NULL),
  (7, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (7, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (7, 3, 'Tempo', '[{"code":"TE","duration_min":45,"note":"20 min · Esfuerzo: 3h race pace · Buen día para probar tu estrategia de combustible (*)."}]', 45, NULL),
  (7, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (7, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":198,"note":"Buen día para probar tu estrategia de combustible (*)."}]', 198, '18 mi'),
  (8, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40,"note":"Buen día para probar tu estrategia de combustible (*)."}]', 40, '4 mi'),
  (8, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (8, 3, 'Hill Fartlek', '[{"code":"HF","duration_min":50,"note":"25 min ondulada: duro en subidas (40-60 min race pace), easy en llano y bajadas"}]', 50, NULL),
  (8, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":70}]', 70, '7 mi'),
  (8, 5, 'Caminata Larga', '[{"code":"HK","duration_min":420,"note":"Caminata en cerro de 6-7 h"}]', 420, NULL),
  (9, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (9, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (9, 3, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x (1 min duro cuesta arriba / 1 min bajada easy) + 3 min trote easy + 15 min tempo @ 3h race pace (65-70%)"}]', 45, NULL),
  (9, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (9, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":220,"note":"Buen día para probar tu estrategia de combustible (*)."}]', 220, '20 mi'),
  (10, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (10, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (10, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (10, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (10, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":110}]', 110, '10 mi'),
  (11, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (11, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (11, 3, 'Hill Fartlek', '[{"code":"HF","duration_min":45,"note":"Hill alternations 20 min: todas las subidas duro (40-60 min race pace), llanos y bajadas moderado @ 3h race pace (65-70%) · Buen día para probar tu estrategia de combustible (*)."}]', 45, NULL),
  (11, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (11, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":242,"note":"Buen día para probar tu estrategia de combustible (*)."}]', 242, '22 mi'),
  (12, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (12, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (12, 3, 'Tempo', '[{"code":"TE","duration_min":40,"note":"2 x 15 min @ 3h race pace (65-70%) con 5 min trote easy entre reps · Buen día para probar tu estrategia de combustible (*)."}]', 40, NULL),
  (12, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":70}]', 70, '7 mi'),
  (12, 5, 'Caminata Larga', '[{"code":"HK","duration_min":420,"note":"Caminata en cerro de 6-7 h"}]', 420, NULL),
  (13, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (13, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (13, 3, 'Hill Fartlek', '[{"code":"HF","duration_min":50,"note":"Hill alternations 25 min: subidas duro (40-60 min race pace), llanos y bajadas @ 3h race pace (65-70%) · Buen día para probar tu estrategia de combustible (*)."}]', 50, NULL),
  (13, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":30}]', 30, '3 mi'),
  (13, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":275,"note":"Buen día para probar tu estrategia de combustible (*)."}]', 275, '25 mi'),
  (14, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":50}]', 50, '5 mi'),
  (14, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (14, 3, 'Tempo', '[{"code":"TE","duration_min":45,"note":"2 x 20 min @ 3h race pace (65-70%) con 5 min trote easy entre reps · Buen día para probar tu estrategia de combustible (*)."}]', 45, NULL),
  (14, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '6 mi'),
  (14, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":132}]', 132, '12 mi'),
  (15, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (15, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (15, 3, 'Aceleraciones', '[{"code":"SU","duration_min":45,"note":"Relaxed surges run: incluí 4 x 2 min @ 1.5h race pace con 3 min trote easy entre"}]', 45, NULL),
  (15, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (15, 5, 'Tirada Larga', '[{"code":"TLM","duration_min":77}]', 77, '7 mi'),
  (16, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":40}]', 40, '4 mi'),
  (16, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":30,"note":"(o descanso)"}]', 30, '3 mi'),
  (16, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":30}]', 30, '3 mi'),
  (16, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":20}]', 20, '2 mi'),
  (16, 5, '¡Tu carrera!', '[{"code":"RC","duration_min":60}]', 60, NULL)
) as s(w, d, name, b, dur, dist)
on conflict (template_id, week_number, day_index) do nothing;

-- ----------------------------------------------------------------------
-- 100K — 100K Ultramarathon
-- ----------------------------------------------------------------------
insert into public.plan_templates
  (code, name, description, goal_type, experience_level, weekly_days, total_weeks, is_pro)
values
  ('100k', '100K Ultramarathon', 'Plan de 16 semanas para 100K trail. 100K son poco más de 60 millas, dos marathons seguidos y un poco más. Prerequisito: Corredor experimentado: 2 sesiones duras por semana habituales, mínimo 70-80 km semanales, al menos 2 ultramaratones completados', 'trail', 'advanced', 6, 16, true)
on conflict (code) do nothing;

with t as (select id from public.plan_templates where code = '100k')
insert into public.template_sessions
  (template_id, week_number, day_index, session_name, blocks, total_duration_min, distance_label, is_deload)
select t.id, w, d, name, b::jsonb, dur, dist, false from t,
(values
  (1, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 2.5 min duro cuesta arriba, trote a punto de partida. Ritmo más rápido sostenible y consistente"}]', 45, NULL),
  (1, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (1, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48,"note":"Con 6 x 20s strides (llano)"}]', 48, '8K'),
  (1, 4, 'Tempo', '[{"code":"TE","duration_min":50,"note":"25 min steady · Esfuerzo: 3h race pace"}]', 50, NULL),
  (1, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (1, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":175}]', 175, '25K'),
  (2, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 3 min duro cuesta arriba, trote a punto de partida. Ritmo más rápido sostenible y consistente"}]', 45, NULL),
  (2, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (2, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (2, 4, 'Tempo', '[{"code":"TE","duration_min":55,"note":"30 min steady @ 3h race pace (60%)"}]', 55, NULL),
  (2, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":72}]', 72, '12K'),
  (2, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":140,"note":"En los últimos 20 min: 10 min @ 2h race pace (80%)"}]', 140, '20K'),
  (3, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"6 x 3 min duro con 90s trote easy entre reps"}]', 45, NULL),
  (3, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (3, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (3, 4, 'Progresivo', '[{"code":"PR","duration_min":50,"note":"20 min @ 3h race pace (65%) + 10 min @ 2h race pace (80%)"}]', 50, NULL),
  (3, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (3, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":210}]', 210, '30K'),
  (4, 1, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"5 x 4 min duro cuesta arriba, trote a punto de partida. Ritmo más rápido sostenible y consistente"}]', 45, NULL),
  (4, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (4, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48,"note":"Con 6 x 20s strides (llano)"}]', 48, '8K'),
  (4, 4, 'Tempo', '[{"code":"TE","duration_min":45,"note":"2 x 20 min steady @ 3h race pace (60%) con 5 min trote easy entre reps · Buen día para probar tu estrategia de combustible (*)."}]', 45, NULL),
  (4, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":72}]', 72, '12K'),
  (4, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":140}]', 140, '20K'),
  (5, 1, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"6 x 4 min duro con 2 min trote easy entre reps"}]', 45, NULL),
  (5, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (5, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (5, 4, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"Alternation: 5 x (1 min @ 1h race pace 90% / 5 min @ 3h race pace 65%)"}]', 45, NULL),
  (5, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (5, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":245}]', 245, '35K'),
  (6, 1, 'Hill Fartlek', '[{"code":"HF","duration_min":55,"note":"30 min: duro en todas las subidas, easy en llanos y bajadas"}]', 55, NULL),
  (6, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (6, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (6, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":48,"note":"Con 6 x 20s strides"}]', 48, '8K'),
  (6, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":72}]', 72, '12K'),
  (6, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":140,"note":"Incluí 45 min @ 3h race pace (65%) · Buen día para probar tu estrategia de combustible (*)."}]', 140, '20K'),
  (7, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (7, 2, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"8-6-6-4 min duro con 2 min trote easy entre reps"}]', 45, NULL),
  (7, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (7, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":36}]', 36, '6K'),
  (7, 5, 'Progresivo', '[{"code":"PR","duration_min":60,"note":"20 min @ 3h race pace (65%) + 20 min @ 2h race pace (80%) · Buen día para probar tu estrategia de combustible (*)."}]', 60, NULL),
  (7, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":280}]', 280, '40K'),
  (8, 1, 'Hill Fartlek', '[{"code":"HF","duration_min":65,"note":"40 min: duro en todas las subidas, easy en llanos y bajadas"}]', 65, NULL),
  (8, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (8, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (8, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60,"note":"Con 6 x 20s strides"}]', 60, '10K'),
  (8, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (8, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":140,"note":"Incluí 60 min @ 3h race pace (65%) · Buen día para probar tu estrategia de combustible (*)."}]', 140, '20K'),
  (9, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (9, 2, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"4 x 7.5 min duro con 2.5 min trote easy entre reps"}]', 45, NULL),
  (9, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (9, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":36}]', 36, '6K'),
  (9, 5, 'Progresivo', '[{"code":"PR","duration_min":60,"note":"20 min @ 3h race pace (65%) + 15 min @ 2h race pace (80%) + 5 min @ 1h race pace (90%) · Buen día para probar tu estrategia de combustible (*)."}]', 60, NULL),
  (9, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":315,"note":"Alternativa: trail marathon como carrera de preparación"}]', 315, '45K'),
  (10, 1, 'Hill Fartlek', '[{"code":"HF","duration_min":65,"note":"40 min: duro en todas las subidas (1h race pace 90%), llanos y bajadas a 3-4h race pace"}]', 65, NULL),
  (10, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (10, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (10, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60,"note":"Con 6 x 20s strides"}]', 60, '10K'),
  (10, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":72}]', 72, '12K'),
  (10, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":175,"note":"Incluí 75 min @ 4h race pace · Buen día para probar tu estrategia de combustible (*)."}]', 175, '25K'),
  (11, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (11, 2, 'Cuestas', '[{"code":"SF","duration_min":45,"note":"4 x 2 min duro cuesta arriba con trote bajada + 25 min tempo @ 2h race pace (80-85%)"}]', 45, NULL),
  (11, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (11, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (11, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":30}]', 30, '5K'),
  (11, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":350}]', 350, '50K'),
  (12, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (12, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (12, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":84}]', 84, '14K'),
  (12, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60,"note":"Con 6 x 20s strides"}]', 60, '10K'),
  (12, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (12, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":210,"note":"Incluí 90 min @ 4h race pace · Buen día para probar tu estrategia de combustible (*)."}]', 210, '30K'),
  (13, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (13, 2, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"3 x 8 min duro con 3 min trote easy entre reps"}]', 45, NULL),
  (13, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (13, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":36}]', 36, '6K'),
  (13, 5, 'Fartlek', '[{"code":"FK","duration_min":45,"note":"Alternation: 3 x (5 min @ 1h race pace 90% / 15 min steady @ 4h race pace)"}]', 45, NULL),
  (13, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":315}]', 315, '45K'),
  (14, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (14, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (14, 3, 'Hill Fartlek', '[{"code":"HF","duration_min":65,"note":"40 min: duro en subidas (1h race pace 90%), llanos y bajadas a 3-4h race pace"}]', 65, NULL),
  (14, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":60}]', 60, '10K'),
  (14, 5, 'Rodaje Easy', '[{"code":"RS","duration_min":72}]', 72, '12K'),
  (14, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":175,"note":"Incluí 60 min @ 4h race pace · Buen día para probar tu estrategia de combustible (*)."}]', 175, '25K'),
  (15, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (15, 2, 'Progresivo', '[{"code":"PR","duration_min":70,"note":"40 min @ 4h race pace + 10 min @ 2h race pace (80%)"}]', 70, NULL),
  (15, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (15, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":36}]', 36, '6K'),
  (15, 5, 'Tempo', '[{"code":"TE","duration_min":55,"note":"30 min steady @ 3h race pace (60%)"}]', 55, NULL),
  (15, 6, 'Tirada Larga', '[{"code":"TLM","duration_min":105}]', 105, '15K'),
  (16, 1, 'Rodaje Easy', '[{"code":"RS","duration_min":48,"note":"En los últimos 20 min: 10 min @ 3h race pace (65-70%)"}]', 48, '8K'),
  (16, 2, 'Rodaje Easy', '[{"code":"RS","duration_min":48}]', 48, '8K'),
  (16, 3, 'Rodaje Easy', '[{"code":"RS","duration_min":36,"note":"Con 4 x 20s strides relajados (llano)"}]', 36, '6K'),
  (16, 4, 'Rodaje Easy', '[{"code":"RS","duration_min":18}]', 18, '3K'),
  (16, 5, '¡Tu carrera!', '[{"code":"RC","duration_min":60}]', 60, NULL)
) as s(w, d, name, b, dur, dist)
on conflict (template_id, week_number, day_index) do nothing;
